// Generated by gencpp from file local_pkg/PosPos.msg
// DO NOT EDIT!


#ifndef LOCAL_PKG_MESSAGE_POSPOS_H
#define LOCAL_PKG_MESSAGE_POSPOS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace local_pkg
{
template <class ContainerAllocator>
struct PosPos_
{
  typedef PosPos_<ContainerAllocator> Type;

  PosPos_()
    : PosX(0.0)
    , PosY(0.0)
    , heading(0.0)  {
    }
  PosPos_(const ContainerAllocator& _alloc)
    : PosX(0.0)
    , PosY(0.0)
    , heading(0.0)  {
  (void)_alloc;
    }



   typedef double _PosX_type;
  _PosX_type PosX;

   typedef double _PosY_type;
  _PosY_type PosY;

   typedef double _heading_type;
  _heading_type heading;





  typedef boost::shared_ptr< ::local_pkg::PosPos_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::local_pkg::PosPos_<ContainerAllocator> const> ConstPtr;

}; // struct PosPos_

typedef ::local_pkg::PosPos_<std::allocator<void> > PosPos;

typedef boost::shared_ptr< ::local_pkg::PosPos > PosPosPtr;
typedef boost::shared_ptr< ::local_pkg::PosPos const> PosPosConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::local_pkg::PosPos_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::local_pkg::PosPos_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::local_pkg::PosPos_<ContainerAllocator1> & lhs, const ::local_pkg::PosPos_<ContainerAllocator2> & rhs)
{
  return lhs.PosX == rhs.PosX &&
    lhs.PosY == rhs.PosY &&
    lhs.heading == rhs.heading;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::local_pkg::PosPos_<ContainerAllocator1> & lhs, const ::local_pkg::PosPos_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace local_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::local_pkg::PosPos_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::local_pkg::PosPos_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::local_pkg::PosPos_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::local_pkg::PosPos_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::local_pkg::PosPos_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::local_pkg::PosPos_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::local_pkg::PosPos_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0c9c4339b79ef16486c4ef9e069204ef";
  }

  static const char* value(const ::local_pkg::PosPos_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0c9c4339b79ef164ULL;
  static const uint64_t static_value2 = 0x86c4ef9e069204efULL;
};

template<class ContainerAllocator>
struct DataType< ::local_pkg::PosPos_<ContainerAllocator> >
{
  static const char* value()
  {
    return "local_pkg/PosPos";
  }

  static const char* value(const ::local_pkg::PosPos_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::local_pkg::PosPos_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 PosX\n"
"float64 PosY\n"
"float64 heading\n"
;
  }

  static const char* value(const ::local_pkg::PosPos_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::local_pkg::PosPos_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.PosX);
      stream.next(m.PosY);
      stream.next(m.heading);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PosPos_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::local_pkg::PosPos_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::local_pkg::PosPos_<ContainerAllocator>& v)
  {
    s << indent << "PosX: ";
    Printer<double>::stream(s, indent + "  ", v.PosX);
    s << indent << "PosY: ";
    Printer<double>::stream(s, indent + "  ", v.PosY);
    s << indent << "heading: ";
    Printer<double>::stream(s, indent + "  ", v.heading);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LOCAL_PKG_MESSAGE_POSPOS_H
