# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from dh_pkg/cam_msg.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class cam_msg(genpy.Message):
  _md5sum = "5fed320ada716dbe6ac3b9244f0ae883"
  _type = "dh_pkg/cam_msg"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """int32 mission
bool is_stop_flag
bool is_dynamic_obs
float32 mission_time
"""
  __slots__ = ['mission','is_stop_flag','is_dynamic_obs','mission_time']
  _slot_types = ['int32','bool','bool','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       mission,is_stop_flag,is_dynamic_obs,mission_time

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(cam_msg, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.mission is None:
        self.mission = 0
      if self.is_stop_flag is None:
        self.is_stop_flag = False
      if self.is_dynamic_obs is None:
        self.is_dynamic_obs = False
      if self.mission_time is None:
        self.mission_time = 0.
    else:
      self.mission = 0
      self.is_stop_flag = False
      self.is_dynamic_obs = False
      self.mission_time = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_i2Bf().pack(_x.mission, _x.is_stop_flag, _x.is_dynamic_obs, _x.mission_time))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 10
      (_x.mission, _x.is_stop_flag, _x.is_dynamic_obs, _x.mission_time,) = _get_struct_i2Bf().unpack(str[start:end])
      self.is_stop_flag = bool(self.is_stop_flag)
      self.is_dynamic_obs = bool(self.is_dynamic_obs)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_i2Bf().pack(_x.mission, _x.is_stop_flag, _x.is_dynamic_obs, _x.mission_time))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 10
      (_x.mission, _x.is_stop_flag, _x.is_dynamic_obs, _x.mission_time,) = _get_struct_i2Bf().unpack(str[start:end])
      self.is_stop_flag = bool(self.is_stop_flag)
      self.is_dynamic_obs = bool(self.is_dynamic_obs)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_i2Bf = None
def _get_struct_i2Bf():
    global _struct_i2Bf
    if _struct_i2Bf is None:
        _struct_i2Bf = struct.Struct("<i2Bf")
    return _struct_i2Bf
